# Nome do Workflow
name: SpotMusic Backend Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Checkout Repo
        uses: actions/checkout@v2

#      - name: Install Requirements
#        run:  pip install flask flask-wtf pytest pytest-cov

#      - name: Unit Test
#        run: |
#          coverage run --source=app -m pytest test.py
#          coverage report -m
#          coverage xml -i
#     - name: SonarCloud Scan
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

#      - name: New Relic License
#        run: |
#          sed -i "s/licensekey/${{ secrets.NEW_RELIC_LICENSE_KEY }}/g" Dockerfile
#      - name: Login to Heroku Container registry
#        env: 
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#        run: heroku container:login

      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: | 
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev/
      - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
        run: | 
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-app:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-app:latest
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to Cloud RUN
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'spotmusic-backend'
          image: ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-app:latest
          env_vars: DB_LOCAL_HOST=${{ secrets.DB_LOCAL_HOST }}, CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME }}, CLOUD_SQL_DATABASE_NAME=${{ secrets.CLOUD_SQL_DATABASE_NAME }}, CLOUD_SQL_PASSWORD=${{ secrets.CLOUD_SQL_PASSWORD }}, CLOUD_SQL_USERNAME=${{ secrets.CLOUD_SQL_USERNAME }}

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
